### ISSUE TITLE
Add Algolia to the REScala Manual

### ISSUE THREAD

**Issue by xingyif** [rescala-lang/REScala#30]
REscala manual: http://guidosalva.github.io/REScala/manual/

Add a search tool to search stuff in the manual

https://community.algolia.com/docsearch/

**Comment by rmgk** [comment]
Thanks for the suggestion!
We tried to evaluate the tool at some point, but they sign-up processes did not immediately work. We did not retry.
We believe our current manual to be quite searchable using existing features, such as browsers full text search.
