### ISSUE TITLE
Found mistyping in manual

### ISSUE THREAD

**Issue by forbid403** [rescala-lang/REScala#31]
Hello.
While reading a manual, I found some mistypings.

In_"The handler is a first class function that receives the events value as a parameter." 
at 1.2.3. Now, observe, remove,
is **events value** means event values? or events values?

In "Inside a signal expression others signals should be accessed with the () operator.",
at 1.2.4. Signal Expressions,
is **others signals** means other signals?

It might leads to misunderstanding of its using.
Thank you.

**Comment by rmgk** [comment]
I clarified the description of event observers. At the time the event fires, there really is just one value, so the handler function is applied to that value.

I also fixed the second typo.

Thanks for reporting!
